### ISSUE TITLE
Remove RoadRunner Dependency

### ISSUE THREAD

**Issue by rowan-mcalpin** [rowan-mcalpin/NextFTC#12]
*Ported from Discord*

Currently NextFTC is thoroughly intertwined with RoadRunner, and I'm not a fan of that. Eventually, I'd like to make a custom path following & trajectory planning implementation that eliminates the need for roadrunner, but before then I still want to minimize the dependency that NextFTC has with RoadRunner.

**Comment by BaronClaps** [comment]
you got this

**Comment by rowan-mcalpin** [comment]
Official update about this

I've joined forces with the developers of Pedro Pathing and I'm switching to integrating with Pedro Pathing instead of with RoadRunner!!!
