### ISSUE TITLE
Conditional Command Support in MeepMeep

### ISSUE THREAD

**Issue by rowan-mcalpin** [rowan-mcalpin/NextFTC#15]
*Ported from Discord*

If not doing #12, add support for conditional commands (`PassiveConditionalCommand` and `BlockingConditionalCommand`) to the `MeepMeepVisualizer`, so users can just schedule routines in their visualizer. 

Basically how it would work (I think) would be it could take an array of booleans to represent the selection for each conditional command (in sequence of how it runs). Alternatively, add an optional parameter for the visualizer preference.

**Comment by BeepBot99** [comment]
You got this

**Comment by rowan-mcalpin** [comment]
Stale

**Comment by rowan-mcalpin** [comment]
Outdated
